version: '3.3'

services:
  db:
    image: mysql:${MYSQL_IMAGE_VERSION:-5.7}
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: joomla
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla

  web:
    depends_on:
      - db
    image: joomla:${JOOMLA_IMAGE_VERSION}
    ports:
      - 8000:80
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomla
      JOOMLA_DB_NAME: joomla
    volumes:
      - web_data:/var/www/html
volumes:
  db_data:
  web_data:
